### ISSUE TITLE
ERROR:  column does not have dimensions, please specify one

### ISSUE THREAD

**Issue by min-mwei** [lanterndata/lantern#197] opened 2023-10-10 17:19 UTC
Looks like there must be at least one row in the table before one could create a lantern index. Take the "hello world" example, 

```
CREATE TABLE small_world (id integer, vector real[3]);
CREATE INDEX ON small_world USING lantern_hnsw (vector);

```
This above will fail with the message in the title.  Of course if one add insert the create table, it works.  

Thanks.

**Comment by Ngalstyan4** [comment] 2023-10-10 17:49
I see. 

You are trying to create an index on an empty table. 
The problem is that the index does not know the dimension of the vectors you will be inserting.

The `CREATE INDEX` statement on an empty table should work fine once you explicitly state dimensions of the vectors in the index as below:
```
CREATE INDEX ON small_world USING lantern_hnsw (vector) WITH (dim = 3);
```

I think you expect to not need the dimension specification because you already specify the dimension of the `real[]` array in `CREATE TABLE statement (`real[3]`)
But postgres actually does not enforce dimensions on arrays and the `3` in `real[3]` ends up just being decorative/documentation. So, our index has no way of picking it up.

Does this fix the issue?

**Comment by min-mwei** [comment] 2023-10-10 18:29
Thanks for the quick response, yes, this addresses this issue.

**Closed** 2023-10-11 17:43 UTC
